title: Welcome to My Personal Website
baseurl: ""  # Ensure this is empty if you're deploying to the root
url: "https://akarce.github.io"  # Your site URL
markdown: kramdown  # Set your markdown processor
theme: minima  # Specify your theme (optional)
